### PR TITLE
Suggested Changes implemented

### PR DESCRIPTION
**Pull request by sanjay14073**
The changes mentioned were addressed this implies that the workflow will be triggered on pull request of every branch.

### CODE REVIEW

**Comment by morris** [comment]
Thanks for the PR! Does this approach handle the "don't deploy on PRs, only checks" requirement correctly?

**Comment by sanjay14073** [comment]
@morris  yes since the deploy job needs the check which inturn means that unless the code doesnt pass the checks  and only if the pr is on the main branch the workflow will be triggered

**Comment by sanjay14073** [comment]
@morris  any update.

**Comment by morris** [comment]
I'm not convinced this fulfills the requirements. It looks like the entire pipeline would be run for every PR 🤔

**Pull request closed without merging**
